### ISSUE TITLE
Theme breaks track selection option sizes

### ISSUE THREAD

**Issue by alashow** [CTalvio/Kaleidochromic#2] opened 2020-11-21 23:54 UTC
![Theme](https://i.imgur.com/yGdZNa8.png)

vs no theme

![No theme](https://i.imgur.com/vbgpytw.png)

Related PR on https://github.com/jellyfin/jellyfin-web/pull/1099

Same issue with [Monochromic](https://github.com/CTalvio/Monochromic)

**Comment by CTalvio** [comment] 2020-11-25 03:29
You created an issue, on a theme, for a cosmetic problem that does not actually _break_ anything (theme and stock behaviour is the same, only element width is different), caused by the stock CSS, for which a fix has already been merged to master for an upcoming release?

Edit: The readme also specifically asks issues to be opened on the Monochromic github page.

**Closed as completed by CTalvio** 2020-11-25 03:29 UTC

**Comment by alashow** [comment] 2020-11-25 03:43
Excuse me for opening an issue. Didn't notice the issue opening policy on the readme.

I reported here because it seems like the theme breaks the fix. i.e On my instance with the latest Jellyfin  _cosmetic_ problem is there only when the theme is applied, but not with the stock theme.

**Comment by CTalvio** [comment] 2020-11-25 17:32
You don't see the problem on stock, because it simply makes the selection box that wide by default. The text simply isn't longer than what it can fit. If it were, you'd see the same thing, maybe... I misread one thing, I though the fix you referred to was recent and not-yet-released, but it is not. Sorry.

My theme reduces that width because most of the time the options aren't pointlessly long, so it looks nicer.

Edit: Actually... The merge you are linking to was about **causing** the behaviour we see. The selections were extending to fit the text BEFORE and the merge forced them to fit and align by cutting off the text.

**Comment by alashow** [comment] 2020-11-25 21:29
Are you sure about #1099 making it shorter? I can see the change from the PRs only commit on my instance and it looks long.

I saw other reports of this issue on Jellyfin GH, and usual solution was to make all selections longer. But maybe making the clip/cut look nicer would help with uglyness? Like a padding on the right to have space between the arrow icon and option text end.

**Comment by CTalvio** [comment] 2020-11-26 17:49
The first image on #1099 shows how when the text is long the dropdowns extend outside the element (the blue box).
![image](https://user-images.githubusercontent.com/4365015/100380220-1b980880-301f-11eb-936d-de0f6a391e9e.png)

The second image, where a user tests the fix, they show how they no longer do that.
![image](https://user-images.githubusercontent.com/4365015/100380261-30749c00-301f-11eb-9bab-39d60c957dc0.png)

Then there is the name and what they actually say about the problem. As well as the [actual linked issue that they are fixing](https://github.com/jellyfin/jellyfin-web/issues/1098)

My theme, makes the ELEMENT (the blue box) even smaller. Because that looks nicer.

What exactly, is it you want changed? Can't you just change the version name to something reasonable? 

Like: "1080p x264"
